---
- name: Install required dependencies (apt)
  apt:
    state: present
    name:
      - sudo
      - git
      - make
      - protobuf-compiler
      - python3-gpg
      - gnupg2
      - python3-pip
      - java-propose-classpath
      - cython3
      - python3-all-dev
      - python3-wheel
      - rustc
      - cargo
      - python3-apt
      - python3-venv
      - python3-levenshtein
      - swig
      - libssl-dev
      - cmake
- name: Create janitor user
  user:
    name: "{{ janitor_user }}"
    generate_ssh_key: yes
    create_home: yes
    system: yes
    home: "{{ janitor_home }}"
- name: Update janitor git repository
  git:
    repo: https://github.com/jelmer/janitor
    dest: "{{ janitor_code_path }}"
    force: yes
  become: yes
  become_user: "{{ janitor_static_owner }}"
- name: Install prerequisites (pip)
  pip:
    name:
      - setuptools-rust
      - breezy@git+https://github.com/breezy-team/breezy
      - wheel
    virtualenv_command: python3 -m venv --system-site-packages
    virtualenv: "{{ janitor_venv }}"
- name: Install required dependencies (pip)
  pip:
    name:
      - "{{ janitor_code_path }}"
    virtualenv_command: python3 -m venv --system-site-packages
    virtualenv: "{{ janitor_venv }}"
  become: "yes"
  become_user: "{{ janitor_static_owner }}"
- name: janitor.conf configuration
  template:
    src: janitor.conf
    dest: "{{ janitor_conf_path }}"
    owner: "{{ janitor_static_owner }}"
- name: janitor proposal templates
  copy:
    src: "{{ janitor_local_proposal_template_path }}"
    dest: "{{ janitor_home }}/proposal-templates"
- name: postgresql credentials
  template:
    src: pgpass
    dest: "{{ janitor_home }}/.pgpass"
    mode: '0600'
    owner: "{{ janitor_user }}"
- name: configuration directory for Breezy
  file:
    state: directory
    path: "{{ janitor_home }}/{{ item }}"
    owner: "{{ janitor_user }}"
  with_items:
    - .config
    - .config/breezy
- name: Breezy Identity
  command: "{{ janitor_venv }}/bin/python -m breezy whoami '{{ janitor_fullname }} <{{ janitor_email }}>'"
  become: yes
  become_user: "{{ janitor_user }}"
  environment:
    PYTHONPATH: "{{ janitor_code_path }}/breezy"
