---
- name: Install dependencies for IRC notify
  apt:
   package:
    - python3-prometheus-client
    - python3-pydle
   state: present
- name: IRC notify systemd file
  template:
   src: irc-notify.service
   dest: /etc/systemd/system/janitor-irc-notify.service
- name: Enable IRC notify systemd
  systemd:
   name: janitor-irc-notify.service
   state: started
   enabled: "yes"
   daemon_reload: "yes"
