---
- name: System file for ognibuild dep server
  template:
    src: ognibuild-dep.service
    dest: /etc/systemd/system/ognibuild-dep.service
- name: Enable systemd for ognibuild dep server
  systemd:
    name: ognibuild-dep.service
    state: started
    enabled: yes
