[package]
name = "janitor"
version = "0.0.0"
authors = ["Jelmer Vernooĳ <jelmer@jelmer.uk>"]
edition = "2021"
description = "Config for the janitor"
license = "GPL-3.0+"
repository = "https://github.com/jelmer/janitor.git"
homepage = "https://github.com/jelmer/janitor"
build = "build.rs"

[dependencies]
chrono = { version = "0.4.26", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
env_logger = "0.10.0"
log = "0.4.19"
protobuf = "3"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.100"
sqlx = { version = "0.6", features = ["postgres", "runtime-async-std-native-tls"] }
stackdriver_logger = { version = "0.8", optional = true }
url = { version = "2.4.0", features = ["serde"] }

[build-dependencies]
protobuf-codegen = "3"
protoc-rust = "^2.0"

[workspace]
members = [ "crates/*" ]

[features]
default = ["gcp"]
gcp = ["stackdriver_logger"]
