[package]
name = "janitor"
version = "0.0.0"
authors = ["Jelmer Vernooĳ <jelmer@jelmer.uk>"]
edition = "2021"
description = "Config for the janitor"
license = "GPL-3.0+"
repository = "https://github.com/jelmer/janitor.git"
homepage = "https://github.com/jelmer/janitor"
build = "build.rs"

[dependencies]
breezyshim = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
clap = { workspace = true, features = ["derive", "env"], optional = true }
env_logger = { workspace = true }
log = { workspace = true }
protobuf = "3"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sqlx = { version = "0.7", features = ["postgres", "runtime-async-std-native-tls"] }
stackdriver_logger = { version = "0.8", optional = true }
url = { workspace = true, features = ["serde"] }
pyo3 = { workspace = true, features = ["auto-initialize"], optional = true }

[workspace.dependencies]
pyo3-asyncio = { version = "0.19" }
pyo3 = { version = "0.19" }
breezyshim = "0.1.4"
log = "0.4"
env_logger = "0.10"
serde = "1.0"
serde_json = "1.0"
url = "2.4"
chrono = "0.4"
# clap > 4.2 requires rustc 1.70, which is not yet in Debian unstable
clap = "<=4.2"

[build-dependencies]
protobuf-codegen = "3"
protoc-rust = "^2.0"

[workspace]
members = [ "crates/*" ]

[features]
default = ["gcp", "cli"]
gcp = ["stackdriver_logger"]
cli = ["dep:clap", "dep:pyo3"]

[[bin]]
name = "janitor-worker"
path = "src/bin/worker.rs"
required-features = ["cli"]
