FROM docker.io/debian:testing-slim AS m4
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update --yes \
 && apt-get install --yes --no-install-recommends \
        apt-file \
        aptitude \
        auto-apt-proxy \
        iproute2 \
 && apt-get clean \
 && apt-file update \
 && apt-file search /usr/share/aclocal/.*.m4 --regex -l | xargs aptitude -y install



FROM docker.io/debian:testing-slim AS build
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

# Enable forward compatibility with newer versions of Python
ENV PYO3_USE_ABI3_FORWARD_COMPATIBILITY="1"

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update --yes \
 && apt-get install --yes --no-install-recommends \
        auto-apt-proxy \
        iproute2 \
 && apt-get upgrade --yes \
 && apt-get satisfy --yes --no-install-recommends \
       ## Standard packages: ./CONTRIBUTING.md
        cargo \
        libgpgme-dev \
        libssl-dev \
        pkg-config \
        protobuf-compiler \
        python3-pip \
       ## Extra packages
        git \
        libpython3-dev \
        python3-breezy \
 && apt-get clean \
 && rm -rf /usr/share/aclocal

COPY ./scripts/ /usr/local/bin/

COPY --from=m4 /usr/share/aclocal /usr/share/aclocal

RUN git clone https://github.com/jelmer/ognibuild.git /build/ognibuild/ \
 && cd /build/ognibuild/ \
 && cargo build --verbose

EXPOSE 9934

ENTRYPOINT ["python3", "-m", "ognibuild.dep_server", "--port=9934", "--listen-address=0.0.0.0"]
