# Pull (Pre-Built):
#   $ docker pull ghcr.io/g0tmi1k/janitor/differ:wip
# Build:
#   $ docker build -t janitor/differ:latest -f Dockerfile_differ .
# Run:
#   $ docker run --rm --publish 9920:9920 --name janitor-differ --volume $( pwd ):/mnt/janitor ghcr.io/g0tmi1k/janitor/differ:wip --config /mnt/janitor/janitor.conf.example
#   $ docker run --rm --publish 9920:9920 --name janitor-differ --volume $( pwd ):/mnt/janitor janitor/differ:latest --config /mnt/janitor/janitor.conf.example
# Troubleshoot:
#   $ docker run -it --rm -p 9920:9920 --entrypoint=/bin/bash ghcr.io/g0tmi1k/janitor/differ:wip
#   $ docker run --interactive --tty --rm --publish 9920:9920 --entrypoint=/bin/bash --volume $( pwd ):/mnt/janitor --workdir /mnt/janitor janitor/differ:latest
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# https://hub.docker.com/_/debian
FROM docker.io/rust:slim-bullseye AS build
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

# Enable forward compatibility with newer versions of Python
ENV PYO3_USE_ABI3_FORWARD_COMPATIBILITY="1"

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update --yes \
 && apt-get install --yes --no-install-recommends \
        auto-apt-proxy \
        iproute2 \
 && apt-get upgrade --yes \
 && apt-get satisfy --yes --no-install-recommends \
       ## Standard packages: ./CONTRIBUTING.md
        cargo \
        libgpgme-dev \
        libssl-dev \
        pkg-config \
        protobuf-compiler \
        python3-pip \
       ## Extra packages
        libpython3-dev \
 && apt-get clean

# Due to PyPi's gpg v1.10.0 needing libgpgme-dev < 1.18.0-3
#COPY ./scripts/ /usr/local/bin/

COPY . /code

RUN pip3 install --upgrade "/code[gcp,differ]" \
 && rm -rf /code

EXPOSE 9920

ENTRYPOINT ["python3", "-m", "janitor.differ", "--port=9920", "--listen-address=0.0.0.0"]
