# Pull (Pre-Built):
#   $ docker pull ghcr.io/g0tmi1k/janitor/archive:wip
# Build:
#   $ docker build -t janitor/archive:latest -f Dockerfile_archive .
# Run:
#   $ docker run --rm --publish 9914:9914 --name janitor-archive ghcr.io/g0tmi1k/janitor/archive:wip
#   $ docker run --rm --publish 9914:9914 --name janitor-archive janitor/archive:latest
# Troubleshoot:
#   $ docker run -it --rm -p 9914:9914 --entrypoint=/bin/bash ghcr.io/g0tmi1k/janitor/archive:wip
#   $ docker run --interactive --tty --rm --publish 9914:9914 --entrypoint=/bin/bash --volume $( pwd ):/mnt/janitor --workdir /mnt/janitor janitor/archive:latest
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# https://hub.docker.com/_/debian
FROM docker.io/debian:testing-slim AS build
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

# Enable forward compatibility with newer versions of Python
ENV PYO3_USE_ABI3_FORWARD_COMPATIBILITY="1"

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update --yes \
 && apt-get install --yes --no-install-recommends \
        auto-apt-proxy \
        iproute2 \
 && apt-get upgrade --yes \
 && apt-get satisfy --yes --no-install-recommends \
       ## Standard packages: ./CONTRIBUTING.md
        cargo \
        libgpgme-dev \
        libssl-dev \
        pkg-config \
        protobuf-compiler \
        python3-pip \
       ## Extra packages
        dpkg-dev \
        g++ \
        git \
        libapt-pkg-dev \
        libpython3-dev \
 && apt-get clean

# Due to PyPi's gpg v1.10.0 needing libgpgme-dev < 1.18.0-3
COPY ./scripts/ /usr/local/bin/

COPY . /code

RUN pip3 install --break-system-packages --upgrade "/code[gcp,archive]" \
 && rm -rf /code

EXPOSE 9914

ENTRYPOINT ["python3", "-m", "janitor.debian.archive", "--port=9914", "--listen-address=0.0.0.0"]
