# Pull (Pre-Built):
#   $ docker pull ghcr.io/jelmer/janitor/publish:latest
# Build:
#   $ docker build -t janitor/publish:latest -f Dockerfile_publish .
# Run:
#   $ docker run --rm --publish 9912:9912 --name janitor-publish ghcr.io/jelmer/janitor/publish:latest
#   $ docker run --rm --publish 9912:9912 --name janitor-publish janitor/publish:latest
# Troubleshoot:
#   $ docker run -it --rm -p 9912:9912 --entrypoint=/bin/bash ghcr.io/jelmer/janitor/publish:latest bash
#   $ docker run --interactive --tty --rm --publish 9912:9912 --entrypoint=/bin/bash --volume $( pwd ):/mnt/janitor --workdir /mnt/janitor janitor/publish:latest
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# https://hub.docker.com/_/debian
FROM docker.io/debian:testing-slim AS build
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

# Enable forward compatibility with newer versions of Python
ENV PYO3_USE_ABI3_FORWARD_COMPATIBILITY="1"

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update --yes \
 && apt-get install --yes --no-install-recommends \
        auto-apt-proxy \
        iproute2 \
 && apt-get upgrade --yes \
 && apt-get satisfy --yes --no-install-recommends \
       ## Standard packages: ./CONTRIBUTING.md
        cargo \
        libgpgme-dev \
        libssl-dev \
        pkg-config \
        protobuf-compiler \
        python3-pip \
       ## Extra packages
        libpython3-dev \
 && apt-get clean

COPY ./scripts/ /usr/local/bin/

COPY . /code

RUN pip3 install --break-system-packages --upgrade "/code[gcp,publish]" \
 && rm -rf /code

EXPOSE 9912

ENTRYPOINT ["python3", "-m", "janitor.publish", "--port=9912", "--listen-address=0.0.0.0"]
