# Pull (Pre-Built):
#   $ docker pull ghcr.io/g0tmi1k/janitor/worker:wip
# Build:
#   $ docker build -t janitor/worker:latest -f Dockerfile_worker .
# Run:
#   $ docker run --rm --publish 8080:8080 --name janitor-worker ghcr.io/g0tmi1k/janitor/worker:wip
#   $ docker run --rm --publish 8080:8080 --name janitor-worker janitor/worker:latest
# Troubleshoot:
#   $ docker run -it --rm -p 8080:8080 --entrypoint=/bin/bash ghcr.io/g0tmi1k/janitor/worker:wip
#   $ docker run --interactive --tty --rm --publish 8080:8080 --entrypoint=/bin/bash --volume $( pwd ):/mnt/janitor --workdir /mnt/janitor janitor/worker:latest
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# https://hub.docker.com/_/debian
FROM docker.io/rust:slim-bullseye AS build
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

ARG DEBIAN_FRONTEND=noninteractive

# Due to PyPi's gpg v1.10.0 needing libgpgme-dev < 1.18.0-3
#   Not needed as no Python!
#COPY ./scripts/ /usr/local/bin/

COPY . /code

COPY autopkgtest-wrapper /usr/local/bin/autopkgtest-wrapper

RUN apt-get update --yes \
 && apt-get install --yes --no-install-recommends \
        auto-apt-proxy \
        iproute2 \
 && apt-get satisfy --yes --no-install-recommends \
       ## Standard packages: ./CONTRIBUTING.md
        cargo \
        libgpgme-dev \
        libssl-dev \
        pkg-config \
        protobuf-compiler \
        #python3-pip \ # Not needed as no Python!
       ## Extra packages
        libpython3-dev \
        python3-minimal \
 && apt-get clean \
 && cd /code \
 && cargo build --verbose --release -p janitor-worker



# https://hub.docker.com/_/debian
FROM docker.io/rust:slim-bullseye
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

# Enable forward compatibility with newer versions of Python
#   Not needed as no Python!
#ENV PYO3_USE_ABI3_FORWARD_COMPATIBILITY="1"

RUN apt-get update --yes \
 && apt-get install --yes --no-install-recommends \
        auto-apt-proxy \
        iproute2 \
 && apt-get upgrade --yes \
 && apt-get satisfy --yes --no-install-recommends \
       ## Extra packages
        apt-file \
        libpython3-dev \
        python3-breezy \
 && apt-file update

COPY --from=build /code/target/release/janitor-worker /bin/janitor-worker

ENV AUTOPKGTEST=/usr/local/bin/autopkgtest-wrapper

EXPOSE 8080

ENTRYPOINT ["/bin/janitor-worker", "--port=8080", "--listen-address=0.0.0.0"]
