[package]
name = "janitor-auto-upload"
version.workspace = true
edition.workspace = true

[dependencies]
futures = "0.3.31"
tokio = { workspace = true, features = ["full"] }
tracing = "0.1.41"
silver-platter = { workspace = true, features = ["debian"] }
